// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: internal/pkg/svcuser/transport/rpc/locale.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Local     string                 `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	Location  string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Lcid      int32                  `protobuf:"varint,5,opt,name=lcid,proto3" json:"lcid,omitempty"`
	Iso639_1  string                 `protobuf:"bytes,6,opt,name=iso639_1,json=iso6391,proto3" json:"iso639_1,omitempty"`
	Iso639_2  string                 `protobuf:"bytes,7,opt,name=iso639_2,json=iso6392,proto3" json:"iso639_2,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *Locale) Reset() {
	*x = Locale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescGZIP(), []int{0}
}

func (x *Locale) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Locale) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Locale) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *Locale) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Locale) GetLcid() int32 {
	if x != nil {
		return x.Lcid
	}
	return 0
}

func (x *Locale) GetIso639_1() string {
	if x != nil {
		return x.Iso639_1
	}
	return ""
}

func (x *Locale) GetIso639_2() string {
	if x != nil {
		return x.Iso639_2
	}
	return ""
}

func (x *Locale) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Locale) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Locales struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Locale `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Locales) Reset() {
	*x = Locales{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Locales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locales) ProtoMessage() {}

func (x *Locales) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locales.ProtoReflect.Descriptor instead.
func (*Locales) Descriptor() ([]byte, []int) {
	return file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescGZIP(), []int{1}
}

func (x *Locales) GetData() []*Locale {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLocalesCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLocalesCmd) Reset() {
	*x = GetLocalesCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocalesCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalesCmd) ProtoMessage() {}

func (x *GetLocalesCmd) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalesCmd.ProtoReflect.Descriptor instead.
func (*GetLocalesCmd) Descriptor() ([]byte, []int) {
	return file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescGZIP(), []int{2}
}

var File_internal_pkg_svcuser_transport_rpc_locale_proto protoreflect.FileDescriptor

var file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73,
	0x76, 0x63, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x02, 0x0a, 0x06, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x63, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c,
	0x63, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x6f, 0x36, 0x33, 0x39, 0x5f, 0x31, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x73, 0x6f, 0x36, 0x33, 0x39, 0x31, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x73, 0x6f, 0x36, 0x33, 0x39, 0x5f, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x73, 0x6f, 0x36, 0x33, 0x39, 0x32, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2d, 0x0a,
	0x07, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x73, 0x43, 0x6d, 0x64, 0x32, 0x47, 0x0a,
	0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x73,
	0x43, 0x6d, 0x64, 0x1a, 0x0f, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescOnce sync.Once
	file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescData = file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDesc
)

func file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescGZIP() []byte {
	file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescOnce.Do(func() {
		file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescData)
	})
	return file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDescData
}

var file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pkg_svcuser_transport_rpc_locale_proto_goTypes = []interface{}{
	(*Locale)(nil),                // 0: locale.Locale
	(*Locales)(nil),               // 1: locale.Locales
	(*GetLocalesCmd)(nil),         // 2: locale.GetLocalesCmd
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_internal_pkg_svcuser_transport_rpc_locale_proto_depIdxs = []int32{
	3, // 0: locale.Locale.createdAt:type_name -> google.protobuf.Timestamp
	3, // 1: locale.Locale.updatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: locale.Locales.data:type_name -> locale.Locale
	2, // 3: locale.LocaleService.GetLocales:input_type -> locale.GetLocalesCmd
	1, // 4: locale.LocaleService.GetLocales:output_type -> locale.Locales
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_pkg_svcuser_transport_rpc_locale_proto_init() }
func file_internal_pkg_svcuser_transport_rpc_locale_proto_init() {
	if File_internal_pkg_svcuser_transport_rpc_locale_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Locale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Locales); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocalesCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_svcuser_transport_rpc_locale_proto_goTypes,
		DependencyIndexes: file_internal_pkg_svcuser_transport_rpc_locale_proto_depIdxs,
		MessageInfos:      file_internal_pkg_svcuser_transport_rpc_locale_proto_msgTypes,
	}.Build()
	File_internal_pkg_svcuser_transport_rpc_locale_proto = out.File
	file_internal_pkg_svcuser_transport_rpc_locale_proto_rawDesc = nil
	file_internal_pkg_svcuser_transport_rpc_locale_proto_goTypes = nil
	file_internal_pkg_svcuser_transport_rpc_locale_proto_depIdxs = nil
}
