stage:
origins:
domain:
creds:
  privatekey:
  publiccert:
httpserver:
  host:
  port:
db:
  user:
  password:
  name:
  host:
  port:
  sslmode:
  timezone:
jwt:
  # example using https://generate-secret.now.sh/32
  secret:
cache:
  auth:
    host:
    password:
    db:
  otp:
    host:
    password:
    db:
elastic:
  addresses:
  username:
  password:
  separator:
kafka:
  clientid:
  brokers:
  version:
  consumer:
    group:
    assigner:
    isuseoldest:
    router:
      separator:
svcuser:
  address:
oauth:
  redirecturl:
  google:
    clientid:
    clientsecret:
    userinfoapi:
    redirecturl:
    scopes:
  facebook:
    clientid:
    clientsecret:
    userinfoapi:
    redirecturl:
    scopes: